Add QuickCheck property to close #2
kc1212/enigma-hs pull request #4
Opened 2016-10-05 22:54 UTC by narrative

Happy Hacktoberfest!

2016-10-06 08:28 UTC, kc1212 requested changes

2016-10-06 08:28 UTC, kc1212 commented on Crypto/Enigma.hs
> +import Test.QuickCheck (Arbitrary(..), elements, shuffle, vectorOf)
Is it possible to move this to the Test.hs file?

2016-10-06 08:28 UTC, kc1212 commented on Crypto/Enigma.hs
> +
See the comment above

2016-10-06 08:32 UTC, kc1212 commented on enigma-hs.cabal
> +                       QuickCheck
Ideally only QuickCheck should be in the test-suite, but I think the cabal file is a bit screwed up, e.g. the executable is in the tests folder. You're welcome to fix it, but that's not necessary for the issue at hand.

2016-10-07 12:48 UTC, narrative commented
Thanks for taking a look!

I moved the instance to `Test.hs` and wrapped it up in a newtype to avoid having an orphan instance.

2016-10-07 12:57 UTC, kc1212 approved these changes

2016-10-07 12:57 UTC, merged